# the file is created for testing

# config.yaml

# General application settings
application:
  name: MyApp
  version: 1.0.0
  environment: development

# Database settings
database:
  host: localhost
  port: 5432
  user: admin
  password: secret

# Logging settings
logging:
  level: DEBUG
  file: /var/log/myapp.log

# Feature flags
features:
  enable_feature_x: true
  enable_feature_y: false

# Nested settings
nested:
  level1:
    level2:
      key1: value1
      key2: value2
